version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/RubyBank_development"
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:15.3
    environment:
      POSTGRES_DB: RubyBank_development
      POSTGRES_PASSWORD: postgres
