databases:
  - name: ruby_bank
    databaseName: ruby_bank
    user: ruby_bank
    region: frankfurt

services:
  - type: web
    name: ruby_bank
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ruby_bank
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: GMAIL_USERNAME
        sync: false
      - key: GMAIL_PASSWORD
        sync: false
      - key: MAILER_HOST
        sync: false
      - key: RACK_ENV
        value: production
    region: frankfurt
